In [ ]:
# 课后练习1

#发现当特征减小时，无关变量变少，数据质量变好，无论用什么模型都能取得比较好的结果

In [46]:
# 课后练习2
## 预测小区住宅价格，评估模型

## 导入包

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
## 准备数据

In [3]:
file_path= "ch05_housing_train.csv" #最好将数据文件放在同一个目录，否则需要给出完整路径
data = np.loadtxt(file_path, delimiter = ",", skiprows=1) # 跳过第一行，因为第一行是变量名
data  

array([[ 0.859,  0.284, -0.969, ...,  2.008,  0.096, -0.547],
       [-0.602,  0.247,  0.089, ..., -1.639,  0.628, -0.52 ],
       [-1.732, -0.373, -0.143, ..., -0.982, -1.363, -3.71 ],
       ...,
       [-0.138, -1.5  , -1.056, ...,  1.451, -0.566, -1.38 ],
       [-0.12 , -1.479, -0.332, ...,  0.407,  1.202, -2.696],
       [ 0.552,  1.371,  0.771, ..., -0.656,  0.257,  1.715]])

In [4]:
data.shape  #一共30个变量，最后一个变量为需要预测的目标变量

(350, 31)

In [21]:
X = data[:,:30]
y = data[:,30]
print(X.shape)
print(y.shape)

(350, 30)
(350,)


In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state= 0)  #把数据拆分成训练集和测试集

In [ ]:
# 建立预测模型
# 普通OLS模型

In [23]:
from sklearn.linear_model import LinearRegression, Lasso, Ridge
lr = LinearRegression()
lr.fit(X_train, y_train)
lr.coef_

array([ 1.95682492,  0.5637386 ,  0.27200138, -0.00659196,  0.05856361,
        0.02225181, -0.00927554,  0.06602453,  0.04366134,  0.0357387 ,
        0.07056654, -0.01496649,  0.06012827,  0.018744  ,  0.05825429,
        0.03107059,  0.01686244, -0.06043998, -0.08384469, -0.00980351,
       -0.06216054, -0.04786145,  0.07998399,  0.09642414,  0.04925928,
        0.05991021,  0.10617173,  0.05969181, -0.03077123, -0.05926183])

In [ ]:
# 评估模型

In [24]:
y_train_hat = lr.predict(X_train)
y_test_hat = lr.predict(X_test)

from sklearn.metrics import mean_squared_error
mse_train = mean_squared_error(y_train, y_train_hat)
mse_test = mean_squared_error(y_test, y_test_hat)
print(f"训练集 mse： {mse_train}")
print(f"测试集 mse:  {mse_test}")

训练集 mse： 0.9313186761059498
测试集 mse:  1.2242967932821884


In [34]:
#建立预测模型
# Ridge模型
rlr = Ridge(alpha=0.5)
rlr.fit(X_train, y_train)
rlr.coef_

array([ 1.95275522,  0.56273341,  0.27109653, -0.00653245,  0.05758574,
        0.02207618, -0.00928026,  0.06592762,  0.04364621,  0.0353799 ,
        0.0700326 , -0.01498902,  0.06030795,  0.01942367,  0.05841646,
        0.03085356,  0.01691131, -0.06010672, -0.08333056, -0.00920607,
       -0.06146648, -0.04727986,  0.0793327 ,  0.09607815,  0.04958865,
        0.05993774,  0.10547293,  0.05985506, -0.03035578, -0.05896664])

In [35]:
#评估模型
y_train_hat = rlr.predict(X_train)
y_test_hat = rlr.predict(X_test)
mse_train = mean_squared_error(y_train_hat, y_train)
mse_test = mean_squared_error(y_test_hat, y_test)
print(f"训练集 mse： {mse_train}")
print(f"测试集 mse:  {mse_test}")

训练集 mse： 0.931337343840274
测试集 mse:  1.2235749283858581


In [31]:
# 可以发现以上两个回归的结果没有太大差别
# 可以尝试调整超参数alpha，看看结果有没有什么差异

In [32]:
#建立预测模型
#Lasso模型
llr = Lasso(alpha=0.1)
llr.fit(X_train, y_train)
llr.coef_

array([ 1.85348463,  0.47692785,  0.15674869, -0.        , -0.        ,
       -0.        , -0.        ,  0.        ,  0.        ,  0.        ,
        0.        , -0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        , -0.        , -0.        ,  0.        ,
       -0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        , -0.        , -0.        ])

In [33]:
y_train_pred = llr.predict(X_train)
y_test_pred = llr.predict(X_test)
mse_train = mean_squared_error(y_train_hat, y_train)
mse_test = mean_squared_error(y_test_hat, y_test)
print(f"训练集 mse： {mse_train}")
print(f"测试集 mse:  {mse_test}")

训练集 mse： 0.9313929686260892
测试集 mse:  1.2229091054185406


In [37]:
# 可以发现以上三个回归的结果没有太大差别,Lasso模型略好一点
# 可以尝试调整超参数alpha，看看结果有没有什么差异

In [38]:
#最终选择Lasso模型
test = np.loadtxt("ch05_housing_test.csv", skiprows=1, delimiter=",")
test.shape

(150, 30)

In [39]:
pred = llr.predict(test)  #预测结果
pred

array([-4.86061593,  2.80260637,  3.03541893,  1.09564706,  0.04870668,
       -1.46392562, -1.27129981,  5.00777021, -2.09256716, -0.98357805,
        0.02208841,  0.06592848, -0.36593021, -0.90080615,  2.11347952,
        1.29518391,  2.28580521, -0.60556423,  0.09694028,  0.62373238,
        1.71399693, -2.54948276,  0.67445064,  1.73015932, -0.33219608,
        2.02332358, -1.22825442, -2.42725627, -2.23479211, -1.72738091,
       -1.3840677 ,  2.61502948, -2.45279434, -0.17864143, -3.92691677,
        2.03825584,  0.02784818,  1.28287382, -3.19644463, -3.20113248,
        3.0091274 ,  2.17288489, -2.52405042,  1.19807663, -2.1064904 ,
        0.3562212 ,  0.19992435, -2.59172351,  1.3248324 , -1.20215084,
       -1.77987221,  0.13908987, -0.28856243,  2.17956836, -2.18285179,
        1.46957495, -0.08830642, -1.82701934, -1.91666902,  2.56340473,
        0.80603219,  2.29710176, -1.5227861 , -1.96718454, -0.87209903,
       -3.84122897, -1.6224092 , -3.94763118, -2.07440253,  1.64

In [44]:
#将结果与真实值进行比较
ground_data = np.loadtxt("ch05_housing_test_truth.csv", skiprows=1, delimiter=",")
y_ground = ground_data[:,30]
y_ground

array([-5.977,  3.882,  2.103,  0.375, -0.48 , -0.512, -1.365,  5.828,
       -4.182, -1.166, -0.287,  0.84 ,  0.945, -1.603,  3.832,  0.477,
        1.382,  0.327,  0.048,  1.035,  2.138, -3.531,  1.844,  3.567,
       -1.712,  2.807, -1.855, -1.49 , -1.709, -1.709, -1.894,  2.826,
       -3.808, -1.43 , -4.869,  2.77 ,  0.705, -0.292, -3.125, -3.777,
        1.736,  0.325, -2.935,  1.189, -0.421,  0.82 , -0.527, -4.029,
        2.605, -2.192, -2.622,  0.63 ,  0.677,  1.574, -3.193,  0.754,
       -1.919, -1.067, -1.614,  4.215,  1.038,  0.95 , -1.768, -0.883,
       -1.963, -2.108, -0.82 , -2.351, -4.113,  2.154, -0.513, -0.988,
        1.931,  4.135,  0.122,  2.974, -1.888,  2.875,  1.631,  0.562,
        3.69 ,  2.874, -1.428,  1.342, -0.483, -0.203, -2.447, -4.892,
        3.331, -4.172,  3.571, -1.949, -1.41 ,  3.119, -0.723, -1.475,
        0.853, -0.177,  2.159,  0.271, -1.367,  2.558, -0.262, -0.357,
       -2.608, -1.66 , -0.367, -0.416,  2.856,  0.311,  2.008,  1.743,
      

In [45]:
mse = mean_squared_error(y_ground, pred)
print(f"最终测试集mse: {mse}")

最终测试集mse: 1.0477642554643183
